name: Acceptance Tests

on:
  push:
    branches:
      - main

# This ensures that if there are multiple pushes, the current run will complete
# and then the latest push will be processed
concurrency:
  group: deployment-pipeline
  cancel-in-progress: false

jobs:
  check-if-commit-is-latest:
    runs-on: ubuntu-latest
    outputs:
    is_latest: ${{ steps.check.outputs.is_latest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch last two commits to compare

      - name: Check if this is the latest commit
        id: check
        run: |
          LATEST_COMMIT=$(git ls-remote origin main | awk '{print $1}')
          CURRENT_COMMIT=$(git rev-parse HEAD)

          echo "Latest commit: $LATEST_COMMIT"
          echo "Current commit: $CURRENT_COMMIT"

          if [[ "$LATEST_COMMIT" == "$CURRENT_COMMIT" ]]; then
            echo "is_latest=true" >> $GITHUB_OUTPUT
          else
            echo "is_latest=false" >> $GITHUB_OUTPUT
          fi

  acceptance-test:
    needs: check-latest
    if: needs.check-latest.outputs.is_latest == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sleep 60s

      - name: Run Acceptance Tests
        run: echo 'running acceptance tests'
