name: Acceptance Tests

on:
  repository_dispatch:
    types: [vercel-deployed]

jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sleep 60s

      - name: Run Acceptance Tests
        run: echo 'running acceptance tests'
